### ISSUE TITLE
[0.4.1] Mod Crashes Server

### ISSUE THREAD

**Issue by Thaumatarge** [user11681/limitless#3]
When I try to run the server, the server crashes before it can reach worldgen/worldload stage.
Tested with limitless being the only mod
[latest.log](https://github.com/user11681/limitless/files/5194697/latest.log)

**Comment by user11681** [comment]
I thought that I fixed that bug. :thinking:

**Comment by Coopyy** [comment]
experiencing same issue

**Comment by user11681** [comment]
The issue is quite clear, but the workaround might be quite hacky. I'll see what I can do.

**Comment by Coopyy** [comment]
much appreciated

**Comment by user11681** [comment]
The problem is actually caused by [a formatting library that this mod uses](https://github.com/user11681/phormat). I fixed and tested it on client and server: no issues.

**Comment by Fogrits** [comment]
Want to point out it's still crashing, but this time without a log. internal server just hangs at "loading world"

**Comment by Fogrits** [comment]
ps: I'm using 0.4.3

**Comment by user11681** [comment]
Could you send me `latest.log` from your `logs` directory?

**Comment by user11681** [comment]
Hm. It might be caused by the server trying to generate very highly enchanted loot.

**Comment by user11681** [comment]
I think that it would be best to move to [a new issue](https://github.com/user11681/limitless/issues/4).
